name: ci

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/login-action@v2
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          if [[ ${{ runner.os }} = "macOS" ]]
          then
            arch="macos"
          elif [[ ${{ runner.os }} = "Linux" ]]
          then
            arch="linux"
          else
            arch="windows"
          fi

          hash=$(wget --quiet -O - https://storage.googleapis.com/flutter_infra_release/releases/releases_$arch.json \
            | jq -r '.current_release.stable')

          version=$(wget --quiet -O - https://storage.googleapis.com/flutter_infra_release/releases/releases_$arch.json \
            | jq -r --arg hash "$hash" '.releases[] | select (.hash | contains($hash)) | .version')

          echo "SDK_VERSION=$version" >> $GITHUB_OUTPUT
        id: flutter

      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            FLUTTER_SDK_VERSION=${{ steps.flutter.outputs.SDK_VERSION }}
          push: ${{ (github.event_name != 'pull_request' && false) || true }}
          tags: |
            avetkhov/flutter:latest
            avetkhov/flutter:${{ steps.flutter.outputs.SDK_VERSION }}
            ghcr.io/${{ github.actor }}/flutter:latest
            ghcr.io/${{ github.actor }}/flutter:${{ steps.flutter.outputs.SDK_VERSION }}

      - uses: peter-evans/dockerhub-description@v3
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: avetkhov/flutter