name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_flutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter_sdk: [3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9, 3.3.10, 3.7.0]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            FLUTTER_SDK_VERSION=${{ matrix.flutter_sdk }}
          push: true
          tags: |
            avetkhov/flutter:${{ matrix.flutter_sdk }}