name: release

on:
  release:
    types: [created]

jobs:
  release_previous:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        flutter_sdk: [3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9, 3.3.10, 3.7.0, 3.7.1, 3.7.2]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            FLUTTER_SDK_VERSION=${{ matrix.flutter_sdk }}
          push: true
          tags: |
            avetkhov/flutter:${{ matrix.flutter_sdk }}
            ghcr.io/${{ github.actor }}/flutter:${{ matrix.flutter_sdk }}

  release_latest:
    needs: ["release_previous"]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          if [[ ${{ runner.os }} = "macOS" ]]
          then
            arch="macos"
          elif [[ ${{ runner.os }} = "Linux" ]]
          then
            arch="linux"
          else
            arch="windows"
          fi

          hash=$(wget --quiet -O - https://storage.googleapis.com/flutter_infra_release/releases/releases_$arch.json \
            | jq -r '.current_release.stable')

          version=$(wget --quiet -O - https://storage.googleapis.com/flutter_infra_release/releases/releases_$arch.json \
            | jq -r --arg hash "$hash" '.releases[] | select (.hash | contains($hash)) | .version')

          echo "SDK_VERSION=$version" >> $GITHUB_OUTPUT
        id: flutter

      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            FLUTTER_SDK_VERSION=${{ steps.flutter.outputs.SDK_VERSION }}
          push: true
          tags: |
            avetkhov/flutter:latest
            avetkhov/flutter:${{ steps.flutter.outputs.SDK_VERSION }}
            ghcr.io/${{ github.actor }}/flutter:latest
            ghcr.io/${{ github.actor }}/flutter:${{ steps.flutter.outputs.SDK_VERSION }}

      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: avetkhov/flutter